CISS411/Controllers/HomeController.cs
using CISS411.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CISS411.Controllers
{
    public class HomeController : Controller
    {
        IModelRepository _repository;
        
        public HomeController(IModelRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index() =>
            View(_repository);   
    }
}

CISS411/Controllers/Web/HomeController.cs
using CISS411.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CISS411.Controllers.Web
{
    public class HomeController : Controller
    {
        IModelRepository _repository;
        
        public HomeController(IModelRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            ViewBag.Title = "Tech Entrepreneurship";
            return View(_repository);
        }
          
    }
}

CISS411/ViewComponents/BookViewComponent.cs
using CISS411.Models.DomainModels;
using CISS411.Models.Interfaces;
using CISS411.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CISS411.ViewComponents
{
    public class BookViewComponent : ViewComponent
    {
        private readonly ILogger<BookViewComponent> _logger;
        private UserManager<Member> _manager;

        public BookViewComponent(ILogger<BookViewComponent> logger, UserManager<Member> manager)
        {
            _logger = logger;
            _manager = manager;
        }

        public async Task<IViewComponentResult> InvokeAsync(IModelRepository _repository)
        {
            try
            {
                var books = await _repository.Books();
                var user = await _manager.GetUserAsync((ClaimsPrincipal)User);
                var current = books.FirstOrDefault(b => b.IsCurrent);
                CheckoutViewModel vm = new CheckoutViewModel
                {
                    Book = current,
                    Member = user
                };
                return View(vm);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Failed to retrieve books: {ex.Message}");
                return View(new Book());
            }
        }
    }
}

CISS411/ViewComponents/EventViewComponent.cs
using CISS411.Models.DomainModels;
using CISS411.Models.Interfaces;
using CISS411.Models.Miscellaneous;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CISS411.ViewComponents
{
    public class EventViewComponent : ViewComponent
    {
        private readonly ILogger<EventViewComponent> _logger;
        private readonly ApplicationDbContext _context;
        private UserManager<Member> _userManager;

        public EventViewComponent(ILogger<EventViewComponent> logger, ApplicationDbContext context, UserManager<Member> manager)
        {
            _logger = logger;
            _context = context;
            _userManager = manager;
        }

        public async Task<IViewComponentResult> InvokeAsync(IModelRepository _repository)
        {
            try
            {
                var events = await _repository.Events();
                var current = events.FirstOrDefault(e => e.IsNext);
                ViewData["UserIsRegistered"] = UserIsRegistered();
                return View(current);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Failed to retrieve events: {ex.Message}");
                return View(new Event());
            }
        }

        private bool UserIsRegistered()
        {
            var registrations = _context.Registrations;
            var userId = _userManager.GetUserId((ClaimsPrincipal)User);
            foreach (var registration in registrations)
            {
                if (registration.UserId == userId)
                    return true;
            }
            return false;
        }
    }
}

CISS411/Views/Home/Index.cshtml
@model IModelRepository


<!-- Container (About Section) -->
<div class="w3-content w3-container w3-padding-64" id="aboutUs">
    <h3 class="w3-center">About Us</h3>
    <p>Tech Entrepreneurship is a first and foremost a social club. We
    want to provide students with the opportunity to meet others who share
    their interest in starting businesses. We also like to learn things, 
    and to share our knowledge with other students.</p>
</div>

<div class="w3-row w3-center w3-dark-grey w3-padding-16" id="Events">
</div>

<!-- Second Parallax Image with Events Text -->
<div class="bgimg-3 w3-display-container w3-opacity-min">
    <div class="w3-display-middle">
        <span class="w3-xxlarge w3-text-white w3-wide wow bounceInDown">GROUP EVENTS</span>
    </div>
</div>
<div class="w3-row w3-center w3-dark-grey w3-padding-16">
</div>

@await Component.InvokeAsync("Event", Model)

<div class="w3-row w3-center w3-dark-grey w3-padding-16" id="Books">
</div>

<!-- Third Parallax Image with Books Text -->
<div class="bgimg-2 w3-display-container w3-opacity-min">
    <div class="w3-display-middle">
        <span class="w3-xxlarge w3-text-white w3-wide wow bounceInDown">BOOK CLUB</span>
    </div>
</div>

@await Component.InvokeAsync("Book", Model)  

<div class="w3-row w3-center w3-dark-grey w3-padding-16">
</div>